server :
  port :  8082

# Mybatis mapper 映射路径配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bkcashier
    username: root
    password: xj@181860118
    serverTimezone: UTC
    driver-class-name: com.mysql.jdbc.Driver
